### ISSUE TITLE
'/shot config reload' gives internal error on spigot 1.12

### ISSUE THREAD

**Issue by robotnikthingy** [Shampaggon/CrackShot#29]
I get this error when I try to use the command /shot config reload

this started happening after I upgraded to spigot 1.12, I hope bugs like this dont spell the end for this plugin

 

[23:43:12] [Server thread/INFO]: RobotnikMan issued server command: /shot config reload
[23:43:12] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'shot' in plugin CrackShot v0.98.4
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-7228328-d603539]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-7228328-d603539]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[minecraft_server.jar:git-Spigot-7228328-d603539]
    at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [minecraft_server.jar:git-Spigot-7228328-d603539]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [minecraft_server.jar:git-Spigot-7228328-d603539]
    at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-7228328-d603539]
    at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-7228328-d603539]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-7228328-d603539]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-7228328-d603539]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server.jar:git-Spigot-7228328-d603539]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [minecraft_server.jar:git-Spigot-7228328-d603539]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-7228328-d603539]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-7228328-d603539]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.UnsupportedOperationException
    at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:46) ~[minecraft_server.jar:git-Spigot-7228328-d603539]
    at org.bukkit.craftbukkit.v1_12_R1.inventory.RecipeIterator.remove(RecipeIterator.java:51) ~[minecraft_server.jar:git-Spigot-7228328-d603539]
    at com.shampaggon.crackshot.CSMinion.clearRecipes(CSMinion.java:75) ~[?:?]
    at com.shampaggon.crackshot.CSDirector.onCommand(CSDirector.java:449) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-7228328-d603539]
    ... 15 more

**Comment by ghost** [comment]
Same thing.

**Comment by ghost** [comment]
If i run the command from the console:

`>shot config reload
[01:22:01 INFO]: [CrackShot] The weapon 'build_base' has an invalid value for It
em_Type!
[01:22:01 WARN]: Unexpected exception while parsing console command "shot config
 reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'shot
' in plugin CrackShot v0.98.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[cra
ftbukkit.jar:git-Bukkit-3819f8d]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
0) ~[craftbukkit.jar:git-Bukkit-3819f8d]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServ
er.java:623) ~[craftbukkit.jar:git-Bukkit-3819f8d]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(Cra
ftServer.java:609) [craftbukkit.jar:git-Bukkit-3819f8d]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java
:403) [craftbukkit.jar:git-Bukkit-3819f8d]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
367) [craftbukkit.jar:git-Bukkit-3819f8d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
650) [craftbukkit.jar:git-Bukkit-3819f8d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:554) [craftbukkit.jar:git-Bukkit-3819f8d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: Result cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[craftbu
kkit.jar:git-Bukkit-3819f8d]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getRecipesFor(CraftServer
.java:1049) ~[craftbukkit.jar:git-Bukkit-3819f8d]
        at com.shampaggon.crackshot.CSMinion.clearRecipes(CSMinion.java:71) ~[?:
?]
        at com.shampaggon.crackshot.CSDirector.onCommand(CSDirector.java:449) ~[
?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[cra
ftbukkit.jar:git-Bukkit-3819f8d]
        ... 8 more`

**Comment by noahcoetsee** [comment]
Please update your CrackShot to the latest version, and reinstall any weapons on there. You must have an error in some of the configuration files.
